FROM node:12
WORKDIR /app
COPY package*.json ./
ARG ENV_TOKEN=RREJfSE9TVD1qZWxhbmkuZGIuZWxlcGhhbnRzcWwuY29tCkRCX1BPUlQ9NTQzMgpEQl9VU0VSPWdtcWlwcmlhCkRCX1BBU1NXT1JEPXFSVFJ4b0FtNnpiSDBzTEJxcEF2RnVmdW9Ld2Z5TFFTCkRCX05BTUU9Z21xaXByaWEKQVBJX1ZFUlNJT049L2FwaS92MQpQT1JUPTMwMDA=
ENV ENV_TOKEN=$ENV_TOKEN
RUN npm install
COPY . .
EXPOSE 3000
RUN npm run build
CMD ["npm", "run", "start"]